[package]
name = "pretty_env_logger"
version = "0.2.0"
description = "a visually pretty env_logger"
repository = "https://github.com/seanmonstar/pretty-env-logger"
authors = ["Sean McArthur <sean@seanmonstar>"]
license = "MIT/Apache-2.0"

[dependencies]
ansi_term = "0.10"
env_logger = "0.5"
log = "0.4"
